openapi: 3.0.3
info:
  title: Rest API платежей
  version: 1.0.0
paths:
  /balance:
    get:
      summary: Получение баланса на счёте
      security:
        - keycloak_oauth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
              required:
                - id
      responses:
        '200':
          description: Баланс на счёте
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: number
                    format: bigdecimal
                required:
                  - balance
    post:
      summary: Осуществление платежа
      security:
        - keycloak_oauth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                sum:
                  type: number
                  format: bigdecimal
                  minimum: 0
                  exclusiveMinimum: false
              required:
                - id
                - sum
      responses:
        '200':
          description: Баланс успешно уменьшен
        '409':
          description: Недостаточно средств

components:
  securitySchemes:
    keycloak_oauth:
      type: oauth2
      description: Keycloak OAuth2 authentication
      flows:
        authorizationCode:
          authorizationUrl: http://localhost:8082/realms/master/protocol/openid-connect/auth
          tokenUrl: http://localhost:8082/realms/master/protocol/openid-connect/token
          scopes:
            openid: OpenID Connect scope
            profile: User profile information
            email: User email address