openapi: 3.0.3
info:
  title: Rest API платежей
  version: 1.0.0
paths:
  /balance:
    get:
      summary: Получение баланса на счёте
      security:
        - ClientCredentialsAuth: []
      responses:
        '200':
          description: Баланс на счёте
          content:
            application/json:
              schema:
                type: object
                properties:
                  balance:
                    type: number
                    format: bigdecimal
                required:
                  - balance
    post:
      summary: Осуществление платежа
      security:
        - ClientCredentialsAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sum:
                  type: number
                  format: bigdecimal
                  minimum: 0
                  exclusiveMinimum: false
              required:
                - sum
      responses:
        '200':
          description: Баланс успешно уменьшен
        '409':
          description: Недостаточно средств

components:
  securitySchemes:
    ClientCredentialsAuth:
      type: oauth2
      description: This API uses OAuth 2.0 with the client credentials grant flow.
      flows:
        clientCredentials:
          tokenUrl: http://localhost:8082/oauth2/token
          scopes:
            read: Grants read access to resources.
            write: Grants write access to resources.