version: "3"
services:
  db:
    image: postgres:17-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=intershop
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  cache:
    image: redis:8-alpine

  rest:
    build:
      target: rest
    ports:
      - '8081:8080'
    depends_on:
      - db
    environment:
      - spring.r2dbc.url=r2dbc:postgresql://db:5432/intershop
      - spring.r2dbc.username=root
      - spring.r2dbc.password=root

  web:
    build:
      target: web
    ports:
      - '8080:8080'
    depends_on:
      - db
      - cache
      - rest
    environment:
      - DB_NAME=intershop
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - spring.r2dbc.url=r2dbc:postgresql://db:5432/intershop
      - spring.r2dbc.username=root
      - spring.r2dbc.password=root
      - spring.liquibase.url=jdbc:postgresql://db:5432/intershop
      - spring.liquibase.username=root
      - spring.liquibase.password=root
      - spring.data.redis.host=cache
      - spring.data.redis.port=6379
      - spring.cache.redis.time-to-live=PT5S
      - REST_HOST=rest
      - REST_PORT=8080