version: "3"
services:
  db:
    image: postgres:17-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=intershop
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  web:
    build: . # https://github.com/cobr123/intershop.git
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - DB_NAME=intershop
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - spring.r2dbc.url=r2dbc:postgresql://db:5432/intershop
      - spring.r2dbc.username=root
      - spring.r2dbc.password=root
      - spring.liquibase.url=jdbc:postgresql://db:5432/intershop
      - spring.liquibase.username=root
      - spring.liquibase.password=root