items:
  image_dir: './items_images'

logging:
  level:
    root: DEBUG

spring:
  application:
    name: web
  liquibase:
    change-log: 'classpath:/db/changelog/liquibase/main.xml'
  security:
    oauth2:
      client:
        registration:
          keycloak-rest-client: # Описание клиента OAuth2
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: rest-client
            client-secret: 8lHWta5ggYFsrJN5eUEKn3j8YmZqLbSl
            scope: profile
            clientAuthenticationMethod: client_secret_post # Способ передачи секрета